# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  HTML_REPORT_PATH: "public"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - test
  - report

before_script:
  - python -V  # Print out python version for debugging
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - export PYTHONPATH=".:$PYTHONPATH"
  - mkdir -p "${HTML_REPORT_PATH}"

lint:
  stage: test
  script:
    - pylint adventofcode

test-2020:
  stage: test
  script:
    - pytest -v -n 4 --color=yes --html="${HTML_REPORT_PATH}/report-2020.html" adventofcode/tests/y2020
  artifacts:
    when: always
    paths:
      - "${HTML_REPORT_PATH}/"

test-2019:
  stage: test
  script:
    - pytest -v -n 4 --color=yes --html="${HTML_REPORT_PATH}/report-2019.html" adventofcode/tests/y2019
  artifacts:
    when: always
    paths:
      - "${HTML_REPORT_PATH}/"

test-2018:
  stage: test
  script:
    - pytest -v -n 4 --color=yes --html="${HTML_REPORT_PATH}/report-2018.html" adventofcode/tests/y2018
  artifacts:
    when: always
    paths:
      - "${HTML_REPORT_PATH}/"

test-2017:
  stage: test
  script:
    - pytest -v -n 4 --color=yes --html="${HTML_REPORT_PATH}/report-2017.html" adventofcode/tests/y2017
  artifacts:
    when: always
    paths:
      - "${HTML_REPORT_PATH}/"

test-2016:
  stage: test
  script:
    - pytest -v -n 4 --color=yes --html="${HTML_REPORT_PATH}/report-2016.html" adventofcode/tests/y2016
  artifacts:
    when: always
    paths:
      - "${HTML_REPORT_PATH}/"

test-2015:
  stage: test
  script:
    - pytest -v -n 4 --color=yes --html="${HTML_REPORT_PATH}/report-2015.html" adventofcode/tests/y2015
  artifacts:
    when: always
    paths:
      - "${HTML_REPORT_PATH}/"

pages:
  stage: report
  rules:
    - if: $CI_COMMIT_REF_SLUG == "master"
      when: always
  script:
    - ls -lh "${HTML_REPORT_PATH}"
    - cp -r adventofcode/static/* "${HTML_REPORT_PATH}/"
    - for report in $(ls "${HTML_REPORT_PATH}" | grep report); do sed -i -e 's/^\(.*<\/ul>\)/    <li><a href="'${report}'">'${report}'<\/a><\li>\n\1/' "${HTML_REPORT_PATH}/index.html"; done
  artifacts:
    paths:
      - "${HTML_REPORT_PATH}"