---

language: python

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: "lint"
      script: PYTHONPATH=".:$PYTHONPATH" pylint adventofcode
    - stage: "test"
      script: PYTHONPATH=".:$PYTHONPATH" pytest -v -n 4 adventofcode/tests/y2020
