---

language: python

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: "pylint"
      script: PYTHONPATH=".:$PYTHONPATH" pylint
    - stage: "pytest - 2020"
      script: PYTHONPATH=".:$PYTHONPATH" pytest -v -n 4 adventofcode/tests/y2020
